receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
#    loglevel: debug

  # Send to native OTLP Jaeger receiver
  otlp:
    endpoint: 'jaeger-all-in-one:7134'
    insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
