receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlphttp]