receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    # Send to native OTLP Jaeger receiver
    loglevel: debug
    otlp:
      endpoint: 'jaeger-all-in-one:4317'
      tls:
        insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]
