receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging/debug:
    loglevel: debug
  logging:
    loglevel: warn

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging]