receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
#    loglevel: debug

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
