receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    # Send to native OTLP Jaeger receiver
    loglevel: debug
  otlphttp:
    endpoint: http://jaeger-all-in-one:4318
#  otlp:
#    endpoint: 'jaeger-all-in-one:4317'

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp,logging]
